version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
      POSTGRES_DB: app-modular
    ports:
      - "5432:5432"
    networks:
      - app_network
    restart: unless-stopped
    volumes:
      - ./storage/postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:latest
    container_name: mongo-nosql
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: app-modular
    ports:
      - "27017:27017"
    networks:
      - app_network
    restart: unless-stopped
    volumes:
      - ./storage/mongo_data:/data/db

  redis:
    image: redis:latest
    container_name: redis-cache
    command: redis-server
    ports:
      - "6379:6379"
    networks:
      - app_network
    restart: unless-stopped
    volumes:
      - ./storage/redis_data:/data

networks:
  app_network:
    driver: bridge